/*
 * generated by Xtext
 */
package fr.inria.diverse.kompren;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class KomprenRuntimeModule extends fr.inria.diverse.kompren.AbstractKomprenRuntimeModule {

}
