/*
* generated by Xtext
*/
package fr.inria.diverse.kompren;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class KomprenStandaloneSetup extends KomprenStandaloneSetupGenerated{

	public static void doSetup() {
		new KomprenStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

