/*
 * generated by Xtext
 */
package fr.inria.diverse.kompren.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class KomprenUiModule extends fr.inria.diverse.kompren.ui.AbstractKomprenUiModule {
	public KomprenUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
