<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="foo" nsURI="http://foo" nsPrefix="foofoo">
    <eClassifiers xsi:type="ecore:EClass" name="A">
      <eStructuralFeatures xsi:type="ecore:EReference" name="b" lowerBound="1" eType="ecore:EClass modelSlice.ecore#/0/B"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fooA" lowerBound="1"
          eType="ecore:EDataType modelSlice.ecore#/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fooo" eType="ecore:EDataType modelSlice.ecore#/2/EChar"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="ecore:EClass modelSlice.ecore#/0/C"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="B" abstract="true" eSuperTypes="modelSlice.ecore#/0/J">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="EAttribute0" eType="ecore:EDataType modelSlice.ecore#/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="f" eType="ecore:EClass modelSlice.ecore#/0/F"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="J"/>
    <eClassifiers xsi:type="ecore:EClass" name="C" eSuperTypes="modelSlice.ecore#/0/B">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="EAttribute1" lowerBound="1"
          eType="ecore:EDataType modelSlice.ecore#/2/EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="D" eSuperTypes="modelSlice.ecore#/0/B">
      <eStructuralFeatures xsi:type="ecore:EReference" name="e" lowerBound="1" upperBound="-1"
          eType="ecore:EClass modelSlice.ecore#/0/E" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="E"/>
    <eClassifiers xsi:type="ecore:EClass" name="F" eSuperTypes="modelSlice.ecore#/0/I"/>
    <eClassifiers xsi:type="ecore:EClass" name="I"/>
  </ecore:EPackage>
  <ecore:EPackage name="ecore" nsURI="http://www.eclipse.org/emf/2002/Ecore" nsPrefix="ecore">
    <eClassifiers xsi:type="ecore:EDataType" name="EDouble" instanceClassName="double"/>
    <eClassifiers xsi:type="ecore:EDataType" name="EBoolean" instanceClassName="boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="EChar" instanceClassName="char"/>
  </ecore:EPackage>
</xmi:XMI>
