/**
 * generated by Xtext
 */
package fr.inria.diverse.kompren.validation;

import fr.inria.diverse.kompren.validation.AbstractKomprenValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class KomprenValidator extends AbstractKomprenValidator {
}
