/*
* generated by Xtext
*/
package fr.inria.diverse.kompren.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class KomprenAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("fr/inria/diverse/kompren/parser/antlr/internal/InternalKompren.tokens");
	}
}
