/**
 * generated by Xtext
 */
package fr.inria.diverse.kompren.serializer;

import fr.inria.diverse.kompren.serializer.AbstractKomprenSyntacticSequencer;

@SuppressWarnings("all")
public class KomprenSyntacticSequencer extends AbstractKomprenSyntacticSequencer {
}
