/**
 * generated by Xtext
 */
package fr.inria.diverse.kompren.serializer;

import fr.inria.diverse.kompren.serializer.AbstractKomprenSemanticSequencer;

@SuppressWarnings("all")
public class KomprenSemanticSequencer extends AbstractKomprenSemanticSequencer {
}
