/*
* generated by Xtext
*/
package fr.inria.diverse.kompren;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class KomprenUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return fr.inria.diverse.kompren.ui.internal.KomprenActivator.getInstance().getInjector("fr.inria.diverse.kompren.Kompren");
	}
	
}
