/**
 * generated by Xtext
 */
package fr.inria.diverse.kompren.ui.contentassist;

import fr.inria.diverse.kompren.ui.contentassist.AbstractKomprenProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class KomprenProposalProvider extends AbstractKomprenProposalProvider {
}
